### ISSUE TITLE
add the option to show system call to vep script

### ISSUE THREAD

**Issue by jayoung** [Bioconductor/ensemblVEP#1]
Hi there,

For troubleshooting purposes, it'd be great to add an option to the ensemblVEP function show the system call that's made to the vep script.   See https://support.bioconductor.org/p/106976/

thanks,

Janet

**Comment by jayoung** [comment]
Thanks - I'll take a look at that later (looks like it's only available in the devel version for now - is that right? In a fresh installation I still have ensemblVEP_1.20.1.  I don't have devel running these days, so will wait until it works its way into the release branch)

**Comment by lshep** [comment]
Yes it is only an option in devel as we consider it a feature enhancement rather than a bug correction.  The release is schedule for the end of April so it should be available soon in release as well.
