### ISSUE TITLE
VEPFlags error

### ISSUE THREAD

**Issue by audyavar** [Bioconductor/ensemblVEP#3]
I installed the latest version of VEP from Github and ensembleVEP from Bioconductor with version 95 of the annotation cache on Centos OS. When I am running the steps from the ensemblVEP R tutorial, I get the following errors. Please advise. 

library(ensemblVEP)
param <- VEPFlags()
Error in validObject(.Object) : 
  invalid class “VEPFlags” object: Ensembl >=88 requires vep script  (not variant_effect_predictor.pl)
param <- VEPFlags(flags=list(host="useastdb.ensembl.org"), version=94)
Error in validObject(.Object) : 
  invalid class “VEPFlags” object: Ensembl >=88 requires vep script  (not variant_effect_predictor.pl)

**Comment by lshep** [comment]
thank you for the report.  We haven't updated the code yet for ensembl 95.  I will work on this and post back when it has been updated.

**Comment by lshep** [comment]
Can you please display the results of running the following command line:
```
which vep
vep --help
```

**Comment by audyavar** [comment]
I fixed the issue. It seems that running ensemblVEP in R needs VEP path added to default bashrc profile.

Best

Akshata

________________________________

**Comment by lshep** [comment]
excellent -  I was actually just typing that suggestion too!

**Comment by HeikoBre** [comment]
I am running into the same problem - however, I have no idea how too add the VEP path to my default bashrc profile? Could you help me set this up?

**Comment by lshep** [comment]
@HeikoBre  what operating system are you using?

**Comment by HeikoBre** [comment]
Dear @lshep I am running Mac OS Mojave Version 10.14.6 on a MacBook Pro. Thank you for your help!

**Comment by LiNk-NY** [comment]
Hi @HeikoBre, 
You should be able to add it to your `~/.bash_profile` on Mac via something like: 
```
echo "$HOME/bin/vep" >> ~/.bash_profile
```
Where the path points to your `vep` installation.

The installation instructions here may be of some help: https://uswest.ensembl.org/info/docs/tools/vep/script/vep_download.html#macos

**Comment by HeikoBre** [comment]
Hi @LiNk-NY ,

If I run the command in terminal it adds the line 

/Users/admin/ensembl-vep/

to my .bash_profile file. Unfortunately, it doesn't change the error I encounter in R... I tried to relaunch R, didn't change anything though...

**Comment by LiNk-NY** [comment]
@HeikoBre 
Make sure you are pointing to the `vep` installation / script and not the folder. The ending of your path has to look like the `vep` you would use to run a command (see example below where `./vep` is used)

```
# Example of VEP command line:
./vep --cache --offline --format vcf --vcf --force_overwrite \
--dir_cache /opt/vep/.vep/ \
--dir_plugins /opt/vep/.vep/Plugins/ \
--input_file /opt/vep/.vep/input/my_input.vcf \
--output_file /opt/vep/.vep/output/my_output.vcf \
--custom /opt/vep/.vep/custom/my_extra_data.bed,BED_DATA,bed,exact,1 \
--plugin dbNSFP,/opt/vep/.vep/Plugins/dbNSFP.gz,ALL
```

Make sure to log out and log back in to apply changes to your `~/.bash_profile`.

**Comment by HeikoBre** [comment]
Thanks, I tried to go through the installation steps again to make sure I didn't have any upstream problems. When using 
`cpanm DBD::mysql`
I encounter a problem. My logfile says "Can't link/include C library 'ssl', 'crypto', aborting." Probably I need to fix this first... However, I couldn't find a quick solution for it...

**Comment by hpages** [comment]
@HeikoBre Maybe [this helps](https://github.com/Bioconductor/BBS/blob/master/Doc/Prepare-macOS-Mojave-HOWTO.md#410-install-the-mysql-client). This document is a step-by-step record of what we install on our Mac builders. 

Then take a look at the next section ([4.11 Install Ensembl VEP script](https://github.com/Bioconductor/BBS/blob/master/Doc/Prepare-macOS-Mojave-HOWTO.md#411-install-ensembl-vep-script)) for the installation of the Ensembl VEP script itself.

Hope this helps.

**Comment by HeikoBre** [comment]
Dear @hpages 

Thank you for your suggestion! I struggle to append /usr/local/opt/mysql-client/bin to PATH in n /etc/profile and /usr/local/opt/mysql-client/lib/pkgconfig to PKG_CONFIG_PATH. 

I can locate the profile file - but I do not see PATH / PKG_CONFIG_PATH anywhere within the file? Is there an easier way to do it?

**Comment by hpages** [comment]
Appending `/usr/local/opt/mysql-client/bin` to the `PATH` can be done by putting the following line:
```
export PATH="$PATH:/usr/local/opt/mysql-client/bin"
```
in `/etc/profile`.

Then next time you need to append again something to the `PATH` (e.g. `/usr/local/ensembl-vep`), replace the above line with:
```
export PATH="$PATH:/usr/local/opt/mysql-client/bin:/usr/local/ensembl-vep"
```
And so on.

Same thing for `PKG_CONFIG_PATH`.

This is basic/generic stuff and our document assumes that the reader is familiar with these things.

H.

**Comment by hpages** [comment]
Hi @HeikoBre, were you able to solve your problem? If not, please open a new issue so we can discuss it further in the new issue. Closed issue like this one don't receive much attention. Thanks!
