### ISSUE TITLE
system perl issue

### ISSUE THREAD

**Issue by jonathonthill** [Bioconductor/ensemblVEP#4]
I have installed vep and am trying to run it from the ensembl-vep bioconductor package. When loading the library, I am getting the following warning:

Warning message:
In system2("perl", .getVepPath(), stdout = TRUE, stderr = TRUE) :
running command ''perl' /usr/local/bin/vep 2>&1' had status 134

When I run the system command directly on the console, I get:

> system("perl /usr/local/bin/vep 2>&1")
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
Referenced from: /Users/jthill/Code/ensembl-vep/Faidx.bundle
Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
Referenced from: /Users/jthill/Code/ensembl-vep/Faidx.bundle
Expected in: flat namespace

sh: line 1: 8906 Abort trap: 6 perl /usr/local/bin/vep 2>&1

On the other hand, when I run the same command on the command line it works fine. I dug a little more, and I found that R is using the system perl ("usr/bin/perl") instead of the ensembl-recommended perlbrew installation. There needs to be a way for ensemblVEP to recognize perlbrew...

**Comment by mtmorgan** [comment]
I guess a work-around would be to `Sys.setenv(PATH=paste("/path/to/perl/brew", Sys.getenv("PATH"), sep=":"))`? But maybe it helps to understand why a different perl is found on the command line than with `system`...

**Comment by hpages** [comment]
I'm not sure how running `system("perl /usr/local/bin/vep 2>&1")` in a fresh R session can fail while at the same time running `perl /usr/local/bin/vep 2>&1` directly in a terminal works. The two should be equivalent. In particular they should obey the same `PATH` to locate the `perl` executable.

Can you please make sure that:
```
Sys.getenv("PATH")
system("which perl")
```
in a fresh R session produce the same output than:
```
echo $PATH
which perl
```
in a terminal.

If they don't, then something is not quite right with your setup.

Thanks,
H.

**Comment by jonathonthill** [comment]
Yeah, I expected them to be the same as well, but here is what I get:

> Sys.getenv("PATH")
[1] "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin:/opt/X11/bin"
> system("which perl")
/usr/bin/perl
>

(…):~ jthill$ echo $PATH
/Users/jthill/perl5/perlbrew/bin:/Users/jthill/perl5/perlbrew/perls/5.26.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/opt/X11/bin
(…):~ jthill$ which perl
/Users/jthill/perl5/perlbrew/perls/5.26.2/bin/perl

I have also seen cases online where others noted the R PATH was not the same as their user PATH. I was able to resolve it yesterday by creating a .Rprofile file to prepend the perlbrew directory to the PATH variable in R. It seems to work, but if there is a better way, I am open to it. In the meantime, I have added the note to the vignette and README in case others run into it.

Thanks,

Jonathon

On Sep 4, 2019, at 10:04 AM, Hervé Pagès <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure how running system("perl /usr/local/bin/vep 2>&1") in a fresh R session can fail while at the same time running perl /usr/local/bin/vep 2>&1 directly in a terminal works. The two should be equivalent. In particular they should obey the same PATH to locate the perl executable.

Can you please make sure that:

Sys.getenv("PATH")
system("which perl")


in a fresh R session produce the same output than:

echo $PATH
which perl


in a terminal.

If they don't, then something is not quite right with your setup.

Thanks,
H.

**Comment by hpages** [comment]
I suspected something like this was going on. Thanks for confirming. I've no idea why the `PATH` you see from R is an altered version of the one you see at the Unix command line, except for the presence of some `.Rprofile` file somewhere that alters or overwrites it. This is not good and I would strongly recommend that you investigate further.

Anyway, do we agree that this is not an ensemblVEP issue per se but an issue with your R setup? FWIW note that this issue will affect any other package that relies on your `PATH` to find things.

H.

**Comment by jayoung** [comment]
I've stumbled on this too. It's driving me crazy.  @jonathonthill - can you clarify which perlbrew directory you added to PATH in your `.Rprofile` file to make it work?

If I start up R in a Mac Terminal window, where all the PERLBREW envs are set, I can run vep through R/ensemblVEP fine.  It's only when I try to use Rstudio or the R Gui that it fails.

Using `Sys.getenv()`, I noticed that if I start up the R GUI or Rstudio, it doesn't see any of the PATH/PERLBREW envs environmental variables I'm setting using `~/.profile`, but starting R in the Terminal window inherits those envs from the terminal session.

Do you guys know if there's a way to get the GUIs to start-up R using the same environment I'd get if I started R from the terminal?  I suspect this solution could get us there
https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x
but I'm a little nervous to edit `/etc/launchd.conf`.  

I'm a fairly recent convert, but had so very much been enjoying using Rstudio until now!

**Comment by jayoung** [comment]
more info here, in case anyone else is trying to figure this out: 
https://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html#I-get-_0060_0060command-not-found_0027_0027-in-the-GUI-yet-it-works-in-the-Terminal-_002d_002d-why_003f

on the Mac, we should not expect the same PATH (etc) inside GUI R as we get from the Terminal

**Comment by mtmorgan** [comment]
I was thinking that you'd set paths in `~/.Rprofile` or (my choice) `~/.Renviron` and that all would be good? But in your previous comment you'd mentioned `.Rprofile`? But maybe not in your home directory? Or maybe it should be in `~/.Renviron`?

**Comment by jayoung** [comment]
Hi Martin,

Sorry that was unclear.  I am editing `~/.Renviron` not a local version of it.  I finally got it working: here's what I added to `~/.Renviron`:

```
### adding to PATH so that ensemblVEP works

PATH=/Users/jayoung/perl5/perlbrew/perls/perl-5.34.0/bin:/Users/jayoung/bin/ensembl-vep-release-104.3:${PATH}

# this component allows it to see my perlbrew-installed version of perl and libs: /Users/jayoung/perl5/perlbrew/perls/perl-5.34.0/bin
# this component allows it to see my installation of vep: /Users/jayoung/bin/ensembl-vep-release-104.3
```

Phew. That was a frustrating few hours.

Janet
