### ISSUE TITLE
VEPFlags error

### ISSUE THREAD

**Issue by FrancescaLonghin** [Bioconductor/ensemblVEP#5]
I installed the latest version of VEP from Github and ensembleVEP from Bioconductor with version 105 of the annotation cache on ubuntu 18.04. When I am running the steps from the ensemblVEP R tutorial, I get the following errors. Please help me!

library(ensemblVEP)
param <- VEPFlags()
Error in validObject(.Object) :
invalid class “VEPFlags” object: Ensembl >=88 requires vep script (not variant_effect_predictor.pl)

**Comment by lshep** [comment]
Thank you for letting us know.  It slipped past us and we have to update ensemblVEP for v105.

**Comment by lshep** [comment]
I pushed up changes to both the release 3.14 (1.36.1) and devel 3.15 (1.37.1) branches of Bioconductor.  Once those propagate through the builders you should be able to use ensembl 105

**Comment by lshep** [comment]
It looks like the new versions propagated. Can you try again and let us know if you continue to have errors trying to use 105
